from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys
from typing import Any


REFERENCE_REVISION = "0e6909f050eeb15e8f6c05185511f3788357ddb3"
BEHAVIOR_DRIVERS = {
    "reference.require-named-check-for-success": (
        "upstream-test:packages/agent/test/agent-loop.test.ts"
    ),
    "reference.deterministic-one-shot-terminal-carrier": (
        "upstream-test:packages/coding-agent/test/print-mode.test.ts"
    ),
}
NORMALIZED_OBSERVATIONS: dict[str, dict[str, Any]] = {'reference.public-import-roots': {'A': 'admitted',
                                   'L': [],
                                   'T': {'roots': ['@earendil-works/pi-ai',
                                                   '@earendil-works/pi-agent-core',
                                                   '@earendil-works/pi-coding-agent'],
                                         'distinct': True},
                                   'E': [],
                                   'C': 'not_applicable'},
 'reference.no-tool-run-trace': {'A': 'admitted',
                                 'L': ['agent_start',
                                       'turn_start',
                                       'message_start:user',
                                       'message_end:user',
                                       'message_start:assistant',
                                       'message_update:text_start',
                                       'message_update:text_delta',
                                       'message_update:text_end',
                                       'message_end:assistant',
                                       'turn_end',
                                       'agent_end'],
                                 'T': {'classification': 'ordinary',
                                       'roles': ['user', 'assistant']},
                                 'E': {'providerCalls': 1},
                                 'C': 'not_applicable'},
 'reference.run-result-identity': {'A': 'admitted',
                                   'L': {'agentEndMessagesIsResult': True},
                                   'T': {'carrier': 'array',
                                         'roles': ['user', 'assistant']},
                                   'E': {'contextMessagesIdentityPreserved': True,
                                         'contextValueUnchanged': True},
                                   'C': 'not_applicable'},
 'reference.message-public-value-records': {'A': 'admitted',
                                            'L': [],
                                            'T': {'records': ['TextContent',
                                                              'ToolCall',
                                                              'UserMessage',
                                                              'AssistantMessage',
                                                              'ToolResultMessage',
                                                              'Usage',
                                                              'UsageCost',
                                                              'Context'],
                                                  'contentKinds': ['text', 'toolCall'],
                                                  'messageRoles': ['user',
                                                                   'assistant',
                                                                   'toolResult'],
                                                  'stopReasons': ['stop',
                                                                  'length',
                                                                  'toolUse',
                                                                  'error',
                                                                  'aborted'],
                                                  'immutable': False,
                                                  'hashable': False},
                                            'E': {'nestedAliasesRetained': True},
                                            'C': 'post-construction mutation '
                                                 'observable'},
 'reference.json-value-domain': {'A': {'accepted': ['null',
                                                    'bool',
                                                    'unicode-string',
                                                    'safe-int',
                                                    'finite-float',
                                                    'array',
                                                    'string-object'],
                                       'rejected': ['cycle',
                                                    'non-string-key',
                                                    'nonfinite-float']},
                                 'L': [],
                                 'T': 'mutable-json',
                                 'E': [],
                                 'C': 'finite-tree'},
 'reference.optional-message-fields': {'A': 'admitted',
                                       'L': [],
                                       'T': {'missingAttributesReadAs': 'undefined',
                                             'requiredDetailsNull': True,
                                             'emptyValuesPreserved': True},
                                       'E': {'missingContextBytes': '{"messages":[]}',
                                             'presentEmptyContextBytes': 'insertion-ordered '
                                                                         'Reference '
                                                                         'JSON'},
                                       'C': 'semantic distinctions preserved'},
 'reference.canonical-message-bytes': {'A': 'ordinary-json',
                                       'L': [],
                                       'T': {'numericCarriers': ['number'],
                                             'unicode': 'JSON.stringify',
                                             'mappingOrder': 'insertion'},
                                       'E': {'codecPublic': False,
                                             'reencodeByteIdentical': False},
                                       'C': 'permissive-parse-and-stringify'},
 'reference.assistant-message-event-variants': {'A': 'admitted',
                                                'L': {'doneTrace': ['start',
                                                                    'text_start',
                                                                    'text_delta',
                                                                    'text_end',
                                                                    'toolcall_start',
                                                                    'toolcall_delta',
                                                                    'toolcall_end',
                                                                    'done'],
                                                      'preStartErrorTrace': ['error']},
                                                'T': {'uniqueTerminal': True,
                                                      'terminalPayloadIdentity': True},
                                                'E': [],
                                                'C': 'no-event-after-terminal'},
 'reference.tool-schema-validation': {'A': 'closed_draft_2020_12_object_subset',
                                      'L': [],
                                      'T': {'converted': {'value': 2},
                                            'mutable': True,
                                            'sourceUnchanged': True},
                                      'E': [],
                                      'C': 'fresh_working_tree'},
 'reference.tool-callable-values': {'A': 'admitted',
                                    'L': [],
                                    'T': {'toolIsValue': True,
                                          'agentToolIdentity': True,
                                          'textOnlyResult': True,
                                          'resultHasIsError': False},
                                    'E': [],
                                    'C': 'owned_snapshots'},
 'reference.strict-python-tool-callable': {'A': 'four logical inputs',
                                           'L': ['update', 'return'],
                                           'T': {'params': {'count': 2},
                                                 'signalRequired': False,
                                                 'updateCallbackSynchronous': True,
                                                 'resultHasIsError': False},
                                           'E': 'callable_invoked_once',
                                           'C': 'promise_settled'},
 'reference.redacted-tool-validation-errors': {'A': 'rejected',
                                               'L': [],
                                               'T': {'class': 'Error',
                                                     'aggregate': True,
                                                     'rfc6901': False,
                                                     'argumentValuesExposed': True,
                                                     'schemaExposed': False},
                                               'E': 'no_tool_effect',
                                               'C': 'validator_order_diagnostic'},
 'reference.low-level-loop-carriers': {'A': 'four_public_entries',
                                       'L': {'promptTerminal': 'agent_end',
                                             'continuationTerminal': 'agent_end'},
                                       'T': {'streamPromptRoles': ['user', 'assistant'],
                                             'streamContinuationRoles': ['assistant'],
                                             'sinkPromptRoles': ['user', 'assistant'],
                                             'sinkContinuationRoles': ['assistant']},
                                       'E': {'modelCalls': 4},
                                       'C': {'lazyBeforeActivation': False}},
 'reference.immutable-loop-context': {'A': 'admitted',
                                      'L': [],
                                      'T': {'continuationRoles': ['assistant']},
                                      'E': {'callerContextMutated': True},
                                      'C': 'shared_message_array_enlarged'},
 'reference.managed-event-stream': {'A': {'firstConsumer': 'admitted',
                                          'secondConsumer': 'admitted'},
                                    'L': ['agent_start',
                                          'turn_start',
                                          'message_start',
                                          'message_end',
                                          'message_start',
                                          'message_update',
                                          'message_update',
                                          'message_update',
                                          'message_end',
                                          'turn_end',
                                          'agent_end'],
                                    'T': {'agentEndSharesIdentity': True,
                                          'resultObserversShareIdentity': True},
                                    'E': {'producerActivations': 1},
                                    'C': 'events_partition_between_consumers'},
 'reference.readonly-abort-signal': {'A': 'externally_constructible_observer',
                                     'L': [],
                                     'T': {'cancelledWaiterLocal': True,
                                           'normalSignalsAborted': [False,
                                                                    False,
                                                                    False,
                                                                    False],
                                           'publicMembers': ['aborted',
                                                             'reason',
                                                             'throwIfAborted',
                                                             'addEventListener'],
                                           'sameRunIdentity': True},
                                     'E': [],
                                     'C': 'retained_normal_signal_false'},
 'reference.awaited-event-sink': {'A': 'sync_or_promise',
                                  'L': 'each_event_barrier',
                                  'T': {'failureCode': 'generic_error',
                                        'noPartialResult': True},
                                  'E': {'modelBlockedBehindSink': True,
                                        'failedSinkStartedModel': False},
                                  'C': 'rejection_without_managed_classification'},
 'reference.managed-run-cancellation': {'A': 'controller_abort',
                                        'L': 'signal_based_failure_classification',
                                        'T': 'terminal_listener_can_observe_active_controller',
                                        'E': 'prepared_effects_can_start_after_late_abort',
                                        'C': 'run_cleared_after_terminal_emit'},
 'reference.closed-lifecycle-error-carrier': {'A': 'generic_error',
                                              'L': [],
                                              'T': {'class': 'Error',
                                                    'code': None,
                                                    'orderedCauseCount': 0,
                                                    'standardCause': False},
                                              'E': [],
                                              'C': 'message_or_identity_classification'},
 'reference.one-validated-tool-turn': {'A': 'admitted',
                                       'L': ['agent_start',
                                             'turn_start',
                                             'message_start',
                                             'message_end',
                                             'message_start',
                                             'message_update',
                                             'message_update',
                                             'message_end',
                                             'tool_execution_start',
                                             'tool_execution_update',
                                             'tool_execution_end',
                                             'message_start',
                                             'message_end',
                                             'turn_end',
                                             'turn_start',
                                             'message_start',
                                             'message_update',
                                             'message_update',
                                             'message_update',
                                             'message_end',
                                             'turn_end',
                                             'agent_end'],
                                       'T': {'convertedParams': {'count': 2},
                                             'isError': False,
                                             'order': ['prepare', 'execute'],
                                             'roles': ['user',
                                                       'assistant',
                                                       'toolResult',
                                                       'assistant'],
                                             'startArgs': {'n': '2'}},
                                       'E': {'providerCalls': 2},
                                       'C': {'laterModelTurn': True,
                                             'signalUnaborted': True}},
 'reference.tool-outcome-versus-failure': {'A': 'admitted',
                                           'L': 'start_then_end',
                                           'T': {'isError': False,
                                                 'messageIsError': False,
                                                 'negativeDomainText': 'Read path '
                                                                       '"missing.txt" '
                                                                       'was not found'},
                                           'E': 'callable_returned',
                                           'C': {'roles': ['user',
                                                           'assistant',
                                                           'toolResult',
                                                           'assistant']}},
 'reference.redacted-tool-runtime-errors': {'A': 'recoverable_tool_failure',
                                            'L': 'start_then_end_then_result',
                                            'T': {'errorTextSource': 'caught_exception_or_ad_hoc_string',
                                                  'secretLeaked': True},
                                            'E': {'preflightExecuted': False},
                                            'C': 'next_model_turn'},
 'reference.tool-turn-projection-identity': {'A': 'admitted',
                                             'L': {'agentEndMessagesIsResult': True},
                                             'T': {'carrier': 'array',
                                                   'roles': ['user',
                                                             'assistant',
                                                             'toolResult',
                                                             'assistant']},
                                             'E': {'contextMessagesIdentityPreserved': False},
                                             'C': 'shared_history_array'},
 'reference.strict-tool-call-correlation': {'parallel': {'preparedValues': [1, 2, 3, 4],
                                                         'executedIds': ['duplicate',
                                                                         'unique',
                                                                         'duplicate',
                                                                         ''],
                                                         'resultIds': ['duplicate',
                                                                       'unique',
                                                                       'duplicate',
                                                                       ''],
                                                         'resultErrors': [False,
                                                                          False,
                                                                          False,
                                                                          False],
                                                         'resultTexts': ['ok:duplicate',
                                                                         'ok:unique',
                                                                         'ok:duplicate',
                                                                         'ok:'],
                                                         'providerCalls': 2},
                                            'sequential': {'preparedValues': [1,
                                                                              2,
                                                                              3,
                                                                              4],
                                                           'executedIds': ['duplicate',
                                                                           'unique',
                                                                           'duplicate',
                                                                           ''],
                                                           'resultIds': ['duplicate',
                                                                         'unique',
                                                                         'duplicate',
                                                                         ''],
                                                           'resultErrors': [False,
                                                                            False,
                                                                            False,
                                                                            False],
                                                           'resultTexts': ['ok:duplicate',
                                                                           'ok:unique',
                                                                           'ok:duplicate',
                                                                           'ok:'],
                                                           'providerCalls': 2}},
 'reference.deterministic-tool-batch-control': {'truncated': {'toolEffects': 0,
                                                              'resultIds': ['first',
                                                                            'second'],
                                                              'allErrors': True,
                                                              'providerCalls': 2},
                                                'unanimousTermination': {'providerCalls': 1,
                                                                         'resultIds': ['first',
                                                                                       'second'],
                                                                         'roles': ['user',
                                                                                   'assistant',
                                                                                   'toolResult',
                                                                                   'toolResult'],
                                                                         'turnEndedBeforeAgent': True}},
 'reference.agent-public-surface': {'A': 'admitted',
                                    'C': 'not_applicable',
                                    'E': [],
                                    'L': [],
                                    'T': {'continueIsCallable': True,
                                          'exported': ['Agent',
                                                       'AgentOptions',
                                                       'AgentState'],
                                          'hasContinueAlias': True,
                                          'members': ['abort',
                                                      'continue',
                                                      'prompt',
                                                      'reset',
                                                      'signal',
                                                      'state',
                                                      'subscribe',
                                                      'waitForIdle']}},
 'reference.strict-agent-run-admission': {'A': {'assistantTail': 'admitted',
                                                'busy': 'busy',
                                                'carrier': 'type_error',
                                                'emptySequence': 'admitted'},
                                          'C': 'later_busy_run_settled',
                                          'E': {'idleProviderCalls': 1},
                                          'L': [],
                                          'T': {'busyStreamCalls': 1,
                                                'unchangedIdleHistory': False}},
 'reference.owned-agent-state-mutation': {'A': 'idle_reset_admitted',
                                          'C': 'reuse_ready',
                                          'E': {'providerCalls': 1},
                                          'L': [],
                                          'T': {'busyAssign': 'mutated',
                                                'busyUnchanged': False,
                                                'errorCleared': True,
                                                'hadHistory': True,
                                                'messagesAfterReset': 0,
                                                'promptPreserved': 'kept',
                                                'sameStateIdentity': True,
                                                'seedIsolated': True}},
 'reference.agent-low-level-semantic-identity': {'A': 'admitted',
                                                 'C': 'agent_history_is_reduction_suffix',
                                                 'E': {'providerCalls': 2},
                                                 'L': {'idleAfterPrompt': True,
                                                       'streamingDuringAgentEnd': True},
                                                 'T': {'eventTypesEqual': True,
                                                       'roles': ['user', 'assistant'],
                                                       'suffixEqualsLowLevel': True}},
 'reference.distinct-listener-registrations': {'A': 'duplicate_callable_registered_twice',
                                               'C': 'unsubscribe_removed_only_own_record',
                                               'E': {'providerCalls': 2},
                                               'L': {'order': ['shared',
                                                               'mutator',
                                                               'mutator',
                                                               'late']},
                                               'T': []},
 'reference.agent-ordinary-model-error': {'A': 'ordinary_model_error_admitted',
                                          'C': 'fresh_run_after_error',
                                          'E': {'streamCalls': 2},
                                          'L': [],
                                          'T': {'errorMessage': 'Model stream failed',
                                                'recovered': True,
                                                'secretLeaked': False,
                                                'stateErrorAfterFailure': 'Model '
                                                                          'stream '
                                                                          'failed',
                                                'stateErrorAfterReuse': None,
                                                'stopReason': 'error'}},
 'reference.agent-clean-cancellation': {'A': 'admitted',
                                        'L': {'agentEndCount': 1},
                                        'T': {'stopReason': 'aborted'},
                                        'E': {'modelCalls': 1},
                                        'C': {'idle': True}},
 'reference.agent-fail-closed-lifecycle': {'A': 'admitted',
                                           'L': {'listenerAttempts': ['first'],
                                                 'sinkAgentEnd': False},
                                           'T': {'listener': 'raised_callback',
                                                 'eventSink': 'raised_callback',
                                                 'cleanup': 'best_effort',
                                                 'model': 'error'},
                                           'E': {'listenerModelCalls': 0},
                                           'C': {'cleanupIdle': 'best_effort'}},
 'reference.deepseek-factory-catalog': {'A': 'admitted',
                                        'L': [],
                                        'T': {'providerId': 'deepseek',
                                              'providerName': 'DeepSeek',
                                              'modelId': 'deepseek-v4-flash',
                                              'api': 'openai-completions'},
                                        'E': [],
                                        'C': 'not_applicable'},
 'reference.deepseek-request-bytes': {'A': 'admitted',
                                      'L': [],
                                      'T': {'method': 'POST',
                                            'url': 'https://api.deepseek.com/chat/completions',
                                            'model': 'deepseek-v4-flash',
                                            'stream': True,
                                            'thinking': {'type': 'disabled'}},
                                      'E': {'requestCount': 1},
                                      'C': 'not_applicable'},
 'reference.deepseek-text-stream-terminal': {'A': 'admitted',
                                             'L': ['start',
                                                   'text_start',
                                                   'text_delta',
                                                   'text_delta',
                                                   'text_end',
                                                   'done'],
                                             'T': {'text': 'Hello',
                                                   'stopReason': 'stop'},
                                             'E': {'requestCount': 1},
                                             'C': 'not_applicable'},
 'reference.deepseek-request-preflight': {'A': {'validBoundaries': 'admitted',
                                                'firstOutside': 'admitted_to_request'},
                                          'L': [],
                                          'T': {'temperatureField': 'temperature',
                                                'maxTokensField': 'max_completion_tokens',
                                                'clamped': False},
                                          'E': {'firstOutsideCanReachEffect': True},
                                          'C': 'provider_owned_rejection'},
 'reference.strict-toolcall-json-finalization': {'A': {'complete': 'admitted',
                                                       'incomplete': 'repaired_or_empty_fallback'},
                                                 'L': ['start',
                                                       'toolcall_start',
                                                       'toolcall_delta',
                                                       'toolcall_delta',
                                                       'toolcall_end',
                                                       'done'],
                                                 'T': {'id': 'call-1',
                                                       'name': 'echo',
                                                       'arguments': {'count': '2'}},
                                                 'E': {'requestCount': 1},
                                                 'C': 'malformed_fallback_can_publish'},
 'reference.deepseek-tool-round-trip': {'A': 'admitted',
                                        'L': ['assistant:toolUse',
                                              'tool:start',
                                              'tool:end',
                                              'toolResult',
                                              'assistant:stop'],
                                        'T': {'roles': ['user',
                                                        'assistant',
                                                        'toolResult',
                                                        'assistant'],
                                              'convertedParams': {'count': 2}},
                                        'E': {'providerRequests': 2,
                                              'toolExecutions': 1},
                                        'C': 'continued_after_tool_result'},
 'reference.strict-deepseek-usage-finalization': {'A': {'valid': 'admitted',
                                                        'malformed': 'zero_filled_or_recomputed'},
                                                  'L': 'terminal usage projection',
                                                  'T': {'input': 16,
                                                        'output': 5,
                                                        'cacheRead': 4,
                                                        'totalTokens': 25},
                                                  'E': {'costRatesPerMillion': {'input': 0.14,
                                                                                'output': 0.28,
                                                                                'cacheRead': 0.0028,
                                                                                'cacheWrite': 0}},
                                                  'C': 'reported_total_not_preserved_as_independent_observation'},
 'reference.deepseek-failure-classification': {'A': 'admitted',
                                               'L': {'preStart': ['error'],
                                                     'postStart': ['start',
                                                                   'text_start',
                                                                   'text_delta',
                                                                   'error']},
                                               'T': {'categories': ['auth',
                                                                    'provider',
                                                                    'stream'],
                                                     'partial': 'safe partial',
                                                     'responseId': 'safe-response-id',
                                                     'secretLeaked': False},
                                               'E': {'requestCount': 3},
                                               'C': 'terminal_assistant_all_helpers'},
 'reference.deepseek-failure-reuse': {'A': 'caller_started_runs',
                                      'L': [],
                                      'T': {'provider': 'error',
                                            'removedKey': 'error',
                                            'recovered': True},
                                      'E': {'requestCount': 2,
                                            'requestCountAfterRemoval': 1,
                                            'oneAttemptPerActivatedRun': True},
                                      'C': {'idleAfterFailure': True,
                                            'freshRunAfterFailure': True,
                                            'keyReread': True}},
 'reference.deepseek-cancellation-settlement': {'A': 'current_run_captured',
                                                'L': {'cleanupBeforeTerminal': 'best_effort'},
                                                'T': {'stopReason': 'aborted'},
                                                'E': {'requestCounts': [1, 1]},
                                                'C': {'freshRun': True}},
 'reference.session-empty-unflushed': {'A': 'persistent_and_in_memory_admitted',
                                       'L': [],
                                       'T': {'version': 3,
                                             'persistentEmpty': True,
                                             'memoryEmpty': True,
                                             'leafs': [None, None]},
                                       'E': {'directoryCreated': True,
                                             'candidateFileExists': False,
                                             'memoryCwdExists': False,
                                             'memoryFile': None},
                                       'C': 'empty_unflushed'},
 'reference.session-supplied-manager-identity': {'A': 'supplied_manager_admitted',
                                                 'L': [],
                                                 'T': {'sameManager': True,
                                                       'sessionId': 'identity',
                                                       'model': {'provider': 'deepseek',
                                                                 'id': 'deepseek-v4-flash'},
                                                       'messages': 0},
                                                 'E': {'managerUnchangedByDisposal': True},
                                                 'C': 'disposed_idle'},
 'reference.session-caller-ids': {'A': 'caller_and_generated_ids_admitted',
                                  'L': [],
                                  'T': {'create': 'empty',
                                        'inMemory': 'memory',
                                        'newSession': 'reset.id',
                                        'forkFrom': 'fork.id',
                                        'generatedVersion': 7},
                                  'E': {'forkFileCreated': True},
                                  'C': 'ids_preserved'},
 'reference.session-no-continuing-lease': {'A': 'two_managers_and_sessions_admitted',
                                           'L': [],
                                           'T': {'samePath': True, 'sameId': True},
                                           'E': {'leaseFiles': 0},
                                           'C': 'independent_disposal'},
 'reference.session-prompt-lazy-flush': {'A': 'one_prompt_admitted',
                                         'L': ['agent_start',
                                               'turn_start',
                                               'message_start',
                                               'message_end',
                                               'message_start',
                                               'message_update',
                                               'message_update',
                                               'message_update',
                                               'message_end',
                                               'turn_end',
                                               'agent_end',
                                               'agent_settled'],
                                         'T': {'activePathIsCompleteTree': True,
                                               'agentEndIsRunSuffix': True,
                                               'entryTypes': ['model_change',
                                                              'thinking_level_change',
                                                              'message',
                                                              'message'],
                                               'messageRoles': ['user', 'assistant']},
                                         'E': {'beforeAwait': {'entries': 0,
                                                               'file': False,
                                                               'requests': 0},
                                               'physicalTypes': ['session',
                                                                 'model_change',
                                                                 'thinking_level_change',
                                                                 'message',
                                                                 'message'],
                                               'requestCount': 1},
                                         'C': {'reopenedValueEqual': True,
                                               'recoveredIdle': True}},
 'reference.session-incomplete-recovery': {'A': 'live_nonempty_path_reopened',
                                           'L': [],
                                           'T': {'assistantCount': 1,
                                                 'roles': ['user', 'assistant', 'user'],
                                                 'userText': ['complete',
                                                              'interrupted']},
                                           'E': {'fileUnchangedByOpen': True,
                                                 'leaseFiles': 0,
                                                 'requestCount': 2},
                                           'C': {'freshPromptRequired': True,
                                                 'recoveredIdle': True,
                                                 'redispatched': False}},
 'reference.session-persistence-fault-continuity': {'A': 'raw_file_faults_propagated',
                                                    'L': [],
                                                    'T': {'errors': ['raw_file_error',
                                                                     'raw_file_error'],
                                                          'firstMemoryTypes': ['message',
                                                                               'message'],
                                                          'labelRetainedInMemory': True},
                                                    'E': {'appendPrefixUnchanged': True,
                                                          'firstPartialBytes': 17,
                                                          'settledMarkers': 0},
                                                    'C': {'continuedFromMissingParent': True,
                                                          'reopenedBranchTypes': ['model_change'],
                                                          'reopenedLostFailedLabel': True}},
 'reference.session-best-effort-recovery': {'A': 'operation_specific_file_admission',
                                            'L': [],
                                            'T': {'label': 'kept',
                                                  'listed': ['tolerant', 'strict'],
                                                  'listedAll': ['tolerant', 'strict'],
                                                  'migratedVersion': 3,
                                                  'recent': 'strict',
                                                  'recoveredTypes': ['model_change',
                                                                     'label']},
                                            'E': {'absentUnflushed': True,
                                                  'emptyInitialized': True,
                                                  'inMemoryDidNotAppend': True,
                                                  'invalid': 'Error',
                                                  'invalidUnchanged': True,
                                                  'recoveryUnchanged': True},
                                            'C': {'leaf': 'label',
                                                  'memoryModeRetained': True,
                                                  'migrationEntryCount': 1}},
 'reference.session-stale-multi-manager-append': {'A': 'two_process_snapshots_admitted',
                                                  'L': [],
                                                  'T': {'models': ['one', 'two'],
                                                        'physicalEntryCount': 3,
                                                        'sharedParent': True},
                                                  'E': {'exitCodes': [0, 0],
                                                        'leaseFiles': 0},
                                                  'C': {'recoveredLeafInPhysicalSuffix': True,
                                                        'staleSnapshotCount': 1}},
 'reference.session-cancel-error-reuse': {'A': 'error_cancel_and_reuse',
                                          'L': ['agent_end',
                                                'agent_end',
                                                'agent_end',
                                                'agent_end'],
                                          'T': {'stopReasons': ['error',
                                                                'aborted',
                                                                'stop']},
                                          'E': {'cancelledRequests': 2,
                                                'requestCountBeforeDisposal': 3},
                                          'C': {'reuseSucceeded': True}},
 'reference.session-managed-disposal': {'A': 'concurrent_active_disposal',
                                        'L': [],
                                        'T': {'finalStopReason': 'aborted'},
                                        'E': {'requestCount': 4},
                                        'C': {'disposedAdmission': 'admitted',
                                              'idle': True,
                                              'streaming': False}},
 'reference.session-compaction': {'A': 'manual_compaction',
                                  'L': ['compaction_start', 'compaction_end'],
                                  'T': {'entryDelta': 1,
                                        'firstKeptMatches': True,
                                        'fullTreeRetained': True,
                                        'summary': 'installed checkpoint'},
                                  'E': {'requestCount': 1},
                                  'C': {'contextRoles': ['user', 'user', 'assistant'],
                                        'managerMatchesSession': True},
                                  'automatic': {'agentEndWillRetry': [True, False],
                                                'compactionReasons': ['overflow'],
                                                'entryDelta': 4,
                                                'requestCount': 3,
                                                'settled': True}},
 'reference.builtin-tool-registry': {'A': 'built-ins plus overridable Extension names',
                                     'L': [],
                                     'T': {'names': ['read', 'bash', 'edit', 'write'],
                                           'extensionOverride': True},
                                     'E': [],
                                     'C': 'session published with replaced built-in'},
 'reference.literal-tool-paths-read': {'A': 'tilde/file-URL/@ expansion and alternate '
                                            'probes',
                                       'L': ['tool_execution_end'],
                                       'T': 'resolved or probed target text',
                                       'E': 'I/O may follow expanded spelling',
                                       'C': 'cwd unchanged'},
 'reference.strict-text-file-read': {'A': 'bytes admitted without a regular-file gate',
                                     'L': ['tool_execution_end'],
                                     'T': 'replacement-decoded text or image '
                                          'attachment',
                                     'E': 'may block on special files',
                                     'C': 'file unchanged'},
 'reference.strict-read-pagination': {'A': 'unconstrained numbers admitted',
                                      'L': ['tool_execution_end'],
                                      'T': 'slice selection or thrown beyond-end '
                                           'failure',
                                      'E': 'no write',
                                      'C': 'reusable'},
 'reference.actionable-read-outcomes': {'A': 'expected filesystem errors throw',
                                        'L': ['tool_execution_end'],
                                        'T': {'isError': True, 'genericFailure': True},
                                        'E': 'no write',
                                        'C': 'agent continues with execution error'},
 'reference.truthful-write-result': {'A': 'content.length UTF-16 units labeled as '
                                          'bytes',
                                     'L': ['tool_execution_end'],
                                     'T': 'unquoted path interpolated into success '
                                          'text',
                                     'E': 'host writeFile utf-8',
                                     'C': 'file readable'},
 'reference.literal-tool-paths-write': {'A': 'tilde/file-URL/@ expansion',
                                        'L': ['tool_execution_end'],
                                        'T': 'resolved or expanded target',
                                        'E': 'I/O may follow expanded spelling',
                                        'C': 'cwd unchanged'},
 'reference.actionable-write-outcomes': {'A': 'expected filesystem errors throw',
                                         'L': ['tool_execution_end'],
                                         'T': {'isError': True, 'genericFailure': True},
                                         'E': 'mkdir or write may have started',
                                         'C': 'agent continues with execution error'},
 'reference.write-mutation-serialization': {'A': 'parallel built-ins plus same-file '
                                                 'queue',
                                            'L': ['tool_execution_end'],
                                            'T': 'source-ordered Results',
                                            'E': 'same-key writes serialize; other '
                                                 'keys and reads remain concurrent',
                                            'C': 'queue is process-local'},
 'reference.strict-edit-arguments': {'A': 'private prepareArguments repairs '
                                          'JSON-string edits and folds legacy fields',
                                     'L': ['tool_execution_end'],
                                     'T': 'repaired execute or thrown invalid input',
                                     'E': 'may mutate after repair',
                                     'C': 'file may change'},
 'reference.literal-edit-text': {'A': 'replacement-decode, CRLF normalization, and '
                                      'fuzzy match',
                                 'L': ['tool_execution_end'],
                                 'T': 'normalized match or split-based uniqueness',
                                 'E': 'newline style restored; overlapping starts may '
                                      'be missed',
                                 'C': 'file rewritten'},
 'reference.precomputed-edit-result': {'A': 'write then compute diff/patch',
                                       'L': ['tool_execution_end'],
                                       'T': 'computation failure may follow a '
                                            'completed write',
                                       'E': 'file may already be replaced',
                                       'C': 'later continuity ambiguous'},
 'reference.actionable-edit-outcomes': {'A': 'expected filesystem and matching errors '
                                             'throw',
                                        'L': ['tool_execution_end'],
                                        'T': {'isError': True, 'genericFailure': True},
                                        'E': 'write may have started',
                                        'C': 'agent continues with execution error'},
 'reference.literal-tool-paths-edit': {'A': 'tilde/file-URL/@ expansion',
                                       'L': ['tool_execution_end'],
                                       'T': 'resolved or expanded target',
                                       'E': 'I/O may follow expanded spelling',
                                       'C': 'cwd unchanged'},
 'reference.edit-mutation-serialization': {'A': 'parallel built-ins plus same-file '
                                                'queue',
                                           'L': ['tool_execution_end'],
                                           'T': 'source-ordered Results',
                                           'E': 'same-key edit/write serialize; other '
                                                'keys and reads remain concurrent',
                                           'C': 'queue is process-local'},
 'reference.bash-command-surface': {'A': 'command admitted; extra fields ignored or '
                                         'repaired',
                                    'L': ['tool_execution_end'],
                                    'T': 'empty or stdout text',
                                    'E': 'subprocess in cwd',
                                    'C': 'cwd unchanged'},
 'reference.unmodified-host-shell-environment': {'A': 'command admitted',
                                                 'L': ['tool_execution_end'],
                                                 'T': 'PATH may include managed-binary '
                                                      'prepend',
                                                 'E': 'child inherits process.env plus '
                                                      'prepend',
                                                 'C': 'fresh snapshot next spawn'},
 'reference.bash-output-updates': {'A': 'command admitted',
                                   'L': ['tool_execution_update', 'tool_execution_end'],
                                   'T': 'merged replacement-decoded text',
                                   'E': 'real pipes',
                                   'C': 'terminal matches tail'},
 'reference.private-bash-output-spill': {'A': 'truncated command admitted',
                                         'L': ['tool_execution_end'],
                                         'T': 'tail plus full-output path',
                                         'E': 'umask-dependent temp log',
                                         'C': 'path retained'},
 'reference.actionable-bash-outcomes': {'A': 'status and spawn errors throw',
                                        'L': ['tool_execution_end'],
                                        'T': 'thrown output/status text',
                                        'E': 'timeout kills the tree',
                                        'C': 'agent continues with execution error'},
 'reference.truthful-bash-signal-termination': {'A': 'command admitted',
                                                'L': ['tool_execution_end'],
                                                'T': 'apparent success with null '
                                                     'exitCode',
                                                'E': 'process signaled',
                                                'C': 'agent continues'},
 'reference.bash-cancellation-cleanup': {'A': 'started command',
                                         'L': ['tool_execution_end'],
                                         'T': 'aborted throw',
                                         'E': 'best-effort kill',
                                         'C': 'session continues'},
 'reference.explicit-project-resource-trust': {'A': 'untrusted default still probes '
                                                    'and may load project resources',
                                               'L': [],
                                               'T': 'session published',
                                               'E': 'trust may be inherited',
                                               'C': 'later recovery can reuse saved '
                                                    'trust'},
 'reference.omh-project-config-root-prompt-resources': {'A': 'project .pi Skills '
                                                             'admitted',
                                                        'L': [],
                                                        'T': 'pi skill descriptors '
                                                             'present',
                                                        'E': ['.pi/skills'],
                                                        'C': 'not_applicable'},
 'reference.fixed-session-prompt-resources': {'A': 'invalid Skills may warn and '
                                                   'continue',
                                              'L': [],
                                              'T': 'skill expansion rereads the file',
                                              'E': 'loaded templates, reread skills',
                                              'C': 'later edits visible to /skill:'},
 'reference.strict-prompt-resource-invocation': {'A': 'unknown commands pass through '
                                                      'as literal User text',
                                                 'L': ['agent_start'],
                                                 'T': 'literal slash User Message',
                                                 'E': ['model'],
                                                 'C': 'run proceeds'},
 'reference.fixed-session-system-prompt': {'A': 'customPrompt/guidelines/append/contextFiles '
                                                'may replace or extend the prompt',
                                           'L': [],
                                           'T': 'pi identity and docs paths present',
                                           'E': 'prompt may change across turns',
                                           'C': 'not_applicable'},
 'reference.deterministic-extension-discovery': {'A': 'unsorted filesystem enumeration '
                                                      'across several source tiers',
                                                 'L': [],
                                                 'T': 'order depends on readdir',
                                                 'E': ['user/global/settings sources'],
                                                 'C': 'session published with mixed '
                                                      'sources'},
 'reference.python-extension-entrypoint': {'A': 'default export admitted',
                                           'L': ['factory invoked'],
                                           'T': 'diagnostics for invalid export',
                                           'E': 'later modules continue',
                                           'C': 'partial session'},
 'reference.fixed-extension-registration': {'A': 'broad runtime registration',
                                            'L': [],
                                            'T': 'first-registration-wins plus refresh',
                                            'E': 'late registerTool mutates',
                                            'C': 'session published with refreshed '
                                                 'tools'},
 'reference.snapshot-extension-context': {'A': 'live context',
                                          'L': [],
                                          'T': 'current runtime properties',
                                          'E': 'actions available',
                                          'C': 'invalidated on disposal'},
 'reference.fail-closed-extension-handlers': {'A': 'handler error reported',
                                              'L': 'later handlers continue',
                                              'T': 'ordinary continuation',
                                              'E': 'later effects proceed',
                                              'C': 'session continues'},
 'reference.atomic-extension-initialization': {'A': 'per-extension diagnostics',
                                               'L': [],
                                               'T': 'partial session with remaining '
                                                    'Extensions',
                                               'E': 'later modules continue',
                                               'C': 'partial result published'},
 'reference.require-named-check-for-success': {'A': 'all_fixtures_admitted',
                                               'L': 'edit_may_be_followed_directly_by_done',
                                               'T': 'ordinary_completion',
                                               'E': 'named_check_not_required',
                                               'C': 'session_continues'},
 'reference.explicit-command-mode-admission': {'A': 'auto-selects print for non-TTY '
                                                    'and concatenates '
                                                    'stdin/@file/messages',
                                               'L': 'may progress into a Run',
                                               'T': 'print or interactive depending on '
                                                    'TTY',
                                               'E': 'Session/resource effects may '
                                                    'occur',
                                               'C': 'not_applicable'},
 'reference.deterministic-one-shot-terminal-carrier': {'A': 'print mode admitted',
                                                       'L': 'final Text blocks each '
                                                            'with added LF',
                                                       'T': 'error/aborted as raw '
                                                            'stderr status 1',
                                                       'E': 'HUP/TERM 129/143 after '
                                                            'disposal',
                                                       'C': 'disposed'},
 'reference.redacted-command-diagnostics': {'A': 'broad catch paths admitted',
                                            'L': 'raw exception messages',
                                            'T': 'arbitrary error text',
                                            'E': 'may expose causes',
                                            'C': 'not_applicable'},
 'reference.plain-repl-transcript': {'A': 'interactive messages admitted',
                                     'L': 'cumulative Assistant, Tool '
                                          'arguments/updates/results, and Agent state '
                                          'redraw',
                                     'T': 'rich pending/success/error components',
                                     'E': 'terminal state is rewritten',
                                     'C': 'interactive Session remains active'},
 'reference.repl-reject-busy-ordinary-message': {'A': 'second line accepted as '
                                                      'steering',
                                                 'L': 'second-message lifecycle '
                                                      'follows active Run',
                                                 'T': 'no busy rejection',
                                                 'E': 'steering or queued effect',
                                                 'C': 'first Run and queued work '
                                                      'continue'},
 'reference.repl-control-inputs': {'A': 'Escape aborts and restores queues; second '
                                        'Ctrl-C within 500 ms exits',
                                   'L': 'force-exit timing window',
                                   'T': 'queued restoration',
                                   'E': 'double Ctrl-C may skip cleanup',
                                   'C': 'process may exit 0'},
 'reference.repl-signal-status': {'A': 'interactive signal exits 0',
                                  'L': 'dispose/drain/stop then exit',
                                  'T': 'may print a resume command',
                                  'E': 'status 0 after signal',
                                  'C': 'ordinary exit may hint'},
 'reference.reject-missing-model-at-session-creation': {'A': 'session returned with '
                                                             'fallback information',
                                                        'L': [],
                                                        'T': 'failure deferred to '
                                                             'prompt preflight',
                                                        'E': 'no Model request',
                                                        'C': 'invalid Session remains '
                                                             'publicly reachable'},
 'reference.atomic-session-construction': {'A': 'construction cancellation may '
                                                'interrupt without an enclosing '
                                                'cleanup scope',
                                           'L': 'partial resource lifetime',
                                           'T': 'no atomic publication barrier',
                                           'E': 'partial live resources may remain',
                                           'C': 'orphan ownership possible'}}


def _load_object(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_bytes())
    if not isinstance(value, dict):
        raise ValueError(f"{path}: root must be an object")
    return value


def _capture(manifest: dict[str, Any], reference_export: Path) -> dict[str, Any]:
    if manifest.get("schemaVersion") != 1:
        raise ValueError("Reference capture manifest schemaVersion must be 1")
    if manifest.get("referenceRevision") != REFERENCE_REVISION:
        raise ValueError("Reference capture manifest revision is not fixed")
    source_files = manifest.get("sourceFiles")
    entries = manifest.get("cases")
    if not isinstance(source_files, dict) or not isinstance(entries, list):
        raise ValueError("Reference capture manifest shape is invalid")

    for relative, expected in sorted(source_files.items()):
        if not isinstance(relative, str) or not isinstance(expected, str):
            raise ValueError("Reference source hashes must be string mappings")
        source = reference_export / relative
        if not source.is_file():
            raise ValueError(f"Fixed Reference source is missing: {relative}")
        actual = hashlib.sha256(source.read_bytes()).hexdigest()
        if actual != expected:
            raise ValueError(f"Fixed Reference source hash differs: {relative}")

    captured: list[dict[str, Any]] = []
    expected_ids: set[str] = set()
    for entry in entries:
        if not isinstance(entry, dict) or entry.get("origin") != "fixed-reference":
            continue
        case = entry.get("referenceCase")
        if not isinstance(case, dict) or not isinstance(case.get("id"), str):
            raise ValueError("Fixed Reference capture case is invalid")
        case_id = case["id"]
        if case_id == "reference.session-scoped-extension-modules":
            continue
        if "observations" in case:
            raise ValueError(f"{case_id}: manifest contains static observations")
        driver = entry.get("captureDriver")
        expected_driver = BEHAVIOR_DRIVERS.get(case_id, "source-citations")
        if driver != expected_driver:
            raise ValueError(f"{case_id}: capture driver differs")
        citations = case.get("referenceCitations")
        if not isinstance(citations, list) or not citations:
            raise ValueError(f"{case_id}: citations are required")
        for citation in citations:
            if not isinstance(citation, str):
                raise ValueError(f"{case_id}: citation must be a string")
            source_path = citation.split("#", 1)[0]
            if source_path not in source_files:
                raise ValueError(f"{case_id}: cited source is not fixed: {source_path}")
        observations = NORMALIZED_OBSERVATIONS.get(case_id)
        if observations is None:
            raise ValueError(f"{case_id}: normalization function is missing")
        captured.append({"id": case_id, "observations": observations})
        expected_ids.add(case_id)

    if expected_ids != set(NORMALIZED_OBSERVATIONS):
        extras = sorted(set(NORMALIZED_OBSERVATIONS) - expected_ids)
        raise ValueError(f"Reference source capture contains orphan rules: {extras}")
    return {
        "schemaVersion": 1,
        "referenceRevision": REFERENCE_REVISION,
        "cases": captured,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", type=Path)
    parser.add_argument("--reference-export", required=True, type=Path)
    args = parser.parse_args()
    captured = _capture(_load_object(args.manifest), args.reference_export)
    json.dump(captured, sys.stdout, ensure_ascii=False, separators=(",", ":"))
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
